-- ===============================================
-- Core positions shared across all environments
-- ===============================================

INSERT INTO position (name, description, base_salary) VALUES
('Software Engineer', 'Develops and maintains software applications', 55000.00),
('Project Manager', 'Leads projects and coordinates teams', 65000.00),
('QA Analyst', 'Ensures software quality through testing', 45000.00),
('DevOps Engineer', 'Manages CI/CD pipelines and infrastructure', 60000.00),
('Product Owner', 'Defines product vision and requirements', 70000.00),
('UI/UX Designer', 'Designs user interfaces and experiences', 50000.00),
('Business Analyst', 'Analyzes business processes and requirements', 55000.00),
('HR Specialist', 'Manages human resources operations', 45000.00),
('Finance Manager', 'Oversees financial operations and reporting', 75000.00),
('Marketing Lead', 'Leads marketing strategies and campaigns', 60000.00),
('Sales Executive', 'Drives sales and customer acquisition', 50000.00),
('Support Engineer', 'Provides technical support to customers', 42000.00),
('Data Scientist', 'Analyzes data and builds predictive models', 70000.00),
('Backend Developer', 'Develops server-side applications', 55000.00),
('Frontend Developer', 'Develops client-side applications', 52000.00),
('Mobile Developer', 'Develops mobile applications', 55000.00),
('Cloud Architect', 'Designs cloud infrastructure solutions', 80000.00),
('Security Analyst', 'Ensures cybersecurity and compliance', 65000.00),
('Database Admin', 'Manages and optimizes databases', 58000.00),
('Network Engineer', 'Manages network infrastructure', 55000.00),
('Scrum Master', 'Facilitates agile processes and ceremonies', 60000.00),
('Content Writer', 'Creates written content for marketing', 40000.00),
('SEO Specialist', 'Optimizes content for search engines', 45000.00),
('Customer Success', 'Ensures customer satisfaction and retention', 48000.00),
('Legal Advisor', 'Provides legal guidance and compliance', 75000.00),
('Operations Manager', 'Manages daily operations', 65000.00),
('Accountant', 'Handles accounting and financial records', 50000.00),
('Office Manager', 'Manages office operations and facilities', 45000.00),
('IT Support', 'Provides IT technical support', 40000.00),
('System Analyst', 'Analyzes and designs IT systems', 58000.00),
('Researcher', 'Conducts research and analysis', 55000.00),
('Trainer', 'Develops and delivers training programs', 45000.00),
('Recruiter', 'Sources and recruits talent', 48000.00),
('Copywriter', 'Writes persuasive marketing copy', 42000.00),
('PR Specialist', 'Manages public relations and media', 50000.00),
('Brand Manager', 'Manages brand strategy and identity', 60000.00),
('Growth Hacker', 'Drives rapid growth through experiments', 55000.00),
('Community Manager', 'Manages online community engagement', 42000.00),
('Event Planner', 'Plans and coordinates events', 45000.00),
('Procurement Lead', 'Manages purchasing and vendor relations', 55000.00),
('Logistics Coordinator', 'Coordinates logistics and shipping', 45000.00),
('Quality Manager', 'Ensures product and process quality', 60000.00),
('Compliance Officer', 'Ensures regulatory compliance', 65000.00),
('Risk Analyst', 'Assesses and mitigates business risks', 60000.00),
('Strategy Lead', 'Develops corporate strategy', 75000.00),
('Innovation Lead', 'Drives innovation initiatives', 70000.00),
('Partnerships Manager', 'Manages strategic partnerships', 60000.00),
('Investor Relations', 'Manages investor communications', 65000.00),
('CSR Manager', 'Manages corporate social responsibility', 55000.00),
('Export Manager', 'Manages export operations', 55000.00),
('Import Manager', 'Manages import operations', 55000.00);
