-- ===============================================
-- Core positions shared across all environments
-- ===============================================

INSERT INTO position (name) VALUES
('Software Engineer'),
('Project Manager'),
('QA Analyst'),
('DevOps Engineer'),
('Product Owner'),
('UI/UX Designer'),
('Business Analyst'),
('HR Specialist'),
('Finance Manager'),
('Marketing Lead'),
('Sales Executive'),
('Support Engineer'),
('Data Scientist'),
('Backend Developer'),
('Frontend Developer'),
('Mobile Developer'),
('Cloud Architect'),
('Security Analyst'),
('Database Admin'),
('Network Engineer'),
('Scrum Master'),
('Content Writer'),
('SEO Specialist'),
('Customer Success'),
('Legal Advisor'),
('Operations Manager'),
('Accountant'),
('Office Manager'),
('IT Support'),
('System Analyst'),
('Researcher'),
('Trainer'),
('Recruiter'),
('Copywriter'),
('PR Specialist'),
('Brand Manager'),
('Growth Hacker'),
('Community Manager'),
('Event Planner'),
('Procurement Lead'),
('Logistics Coordinator'),
('Quality Manager'),
('Compliance Officer'),
('Risk Analyst'),
('Strategy Lead'),
('Innovation Lead'),
('Partnerships Manager'),
('Investor Relations'),
('CSR Manager'),
('Export Manager'),
('Import Manager');
