#!/bin/bash

API_URL="http://localhost:8080/api/v1/auth/signup"

# Solo registros con employee_id válidos (1-50)
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"alan.turing@bizflowerp.com","name":"Alan","password":"admin123","employee_id":6}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"ada.lovelace@bizflowerp.com","name":"Ada","password":"admin234","employee_id":5}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"grace.hopper@bizflowerp.com","name":"Grace","password":"manager345","employee_id":7}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"katherine.johnson@bizflowerp.com","name":"Katherine","password":"user345","employee_id":8}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"tim.bernerslee@bizflowerp.com","name":"Tim","password":"manager456","employee_id":9}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"linus.torvalds@bizflowerp.com","name":"Linus","password":"user456","employee_id":10}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"margaret.hamilton@bizflowerp.com","name":"Margaret","password":"manager567","employee_id":11}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"john.vonneumann@bizflowerp.com","name":"John","password":"manager678","employee_id":12}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"dennis.ritchie@bizflowerp.com","name":"Dennis","password":"user678","employee_id":13}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"donald.knuth@bizflowerp.com","name":"Donald","password":"manager789","employee_id":14}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"marie.curie@bizflowerp.com","name":"Marie","password":"user789","employee_id":15}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"albert.einstein@bizflowerp.com","name":"Albert","password":"manager890","employee_id":16}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"isaac.newton@bizflowerp.com","name":"Isaac","password":"user890","employee_id":17}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"stephen.hawking@bizflowerp.com","name":"Stephen","password":"manager901","employee_id":18}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"richard.feynman@bizflowerp.com","name":"Richard","password":"user901","employee_id":19}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"niels.bohr@bizflowerp.com","name":"Niels","password":"manager012","employee_id":20}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"galileo.galilei@bizflowerp.com","name":"Galileo","password":"user012","employee_id":21}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"nikola.tesla@bizflowerp.com","name":"Nikola","password":"manager123","employee_id":22}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"rosalind.franklin@bizflowerp.com","name":"Rosalind","password":"user123","employee_id":23}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"carl.sagan@bizflowerp.com","name":"Carl","password":"manager234","employee_id":24}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"michael.jordan@bizflowerp.com","name":"Michael","password":"user234","employee_id":25}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"serena.williams@bizflowerp.com","name":"Serena","password":"manager345","employee_id":26}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"usain.bolt@bizflowerp.com","name":"Usain","password":"user345","employee_id":27}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"simone.biles@bizflowerp.com","name":"Simone","password":"manager456","employee_id":28}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"lionel.messi@bizflowerp.com","name":"Lionel","password":"user456","employee_id":29}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"cristiano.ronaldo@bizflowerp.com","name":"Cristiano","password":"manager567","employee_id":30}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"roger.federer@bizflowerp.com","name":"Roger","password":"user567","employee_id":31}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"rafael.nadal@bizflowerp.com","name":"Rafael","password":"manager678","employee_id":32}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"pele.nascimento@bizflowerp.com","name":"Pele","password":"user678","employee_id":33}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"diego.maradona@bizflowerp.com","name":"Diego","password":"manager789","employee_id":34}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"simone.weil@bizflowerp.com","name":"Simone","password":"user789","employee_id":35}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"florence.nightingale@bizflowerp.com","name":"Florence","password":"manager890","employee_id":36}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"jane.goodall@bizflowerp.com","name":"Jane","password":"user890","employee_id":37}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"sally.ride@bizflowerp.com","name":"Sally","password":"manager901","employee_id":38}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"neil.armstrong@bizflowerp.com","name":"Neil","password":"user901","employee_id":39}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"yuri.gagarin@bizflowerp.com","name":"Yuri","password":"manager012","employee_id":40}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"valentina.tereshkova@bizflowerp.com","name":"Valentina","password":"user012","employee_id":41}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"amelia.earhart@bizflowerp.com","name":"Amelia","password":"manager123","employee_id":42}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"steve.jobs@bizflowerp.com","name":"Steve","password":"user123","employee_id":43}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"bill.gates@bizflowerp.com","name":"Bill","password":"manager234","employee_id":44}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"mark.zuckerberg@bizflowerp.com","name":"Mark","password":"user234","employee_id":45}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"jeff.bezos@bizflowerp.com","name":"Jeff","password":"manager345","employee_id":46}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"elon.musk@bizflowerp.com","name":"Elon","password":"user345","employee_id":47}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"larry.page@bizflowerp.com","name":"Larry","password":"manager456","employee_id":48}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"sergey.brin@bizflowerp.com","name":"Sergey","password":"user456","employee_id":49}'
curl -X POST $API_URL -H "Content-Type: application/json" -d '{"email":"sheryl.sandberg@bizflowerp.com","name":"Sheryl","password":"manager567","employee_id":50}'
